#!/usr/bin/env bash
# setup-claude-gateway.sh
# Installs a local model-alias proxy for Claude Desktop then configures the app
# to use it.  All you need is: node, a grid.ai API key, and this script.
set -euo pipefail

# ── tuneable config ────────────────────────────────────────────────────────────
GATEWAY_NAME="Harshpreet's gateway"
PROXY_PORT=3456
UPSTREAM="https://grid.ai.juspay.net"
PROXY_API_KEY="sk-litellm"           # key Claude Desktop uses to talk to OUR proxy
PROFILE_ID="00000000-0000-4000-8000-000000000114"

# Model alias map (alias → real upstream model).
# Rules: alias MUST contain claude/sonnet/opus/haiku; must NOT contain
# kimi/glm/minimax/gpt/gemini/qwen/deepseek/grok/llama/moonshot (Claude
# Desktop's client-side blocklist in app.asar/C3()).
# Two parallel arrays — bash 3.2 compatible (macOS default shell).
ALIAS_KEYS=("claude-sonnet-km"    "claude-sonnet-gl" "claude-haiku-gl-flash"   "claude-opus-mm"         "claude-opus-ol" "claude-haiku-of")
ALIAS_VALS=("kimi-latest"         "glm-latest"       "glm-flash-experimental"  "minimaxai/minimax-m2"   "open-large"     "open-fast")

PROXY_DIR="$HOME/.config/claude-gateway"
PROXY_JS="$PROXY_DIR/proxy.js"
PROXY_ENV="$PROXY_DIR/.env"
PROXY_LOG="$PROXY_DIR/proxy.log"
LAUNCHD_PLIST="$HOME/Library/LaunchAgents/net.juspay.claude-gateway.plist"
LAUNCHD_LABEL="net.juspay.claude-gateway"

NORMAL_DIR="$HOME/Library/Application Support/Claude"
THIRD_PARTY_DIR="$HOME/Library/Application Support/Claude-3p"
CONFIG_LIB="$THIRD_PARTY_DIR/configLibrary"

# ── helpers ───────────────────────────────────────────────────────────────────
die()     { echo "ERROR: $*" >&2; exit 1; }
info()    { echo "  $*"; }
require() { command -v "$1" &>/dev/null || die "'$1' not found — please install it"; }

write_json() {
  mkdir -p "$(dirname "$1")"
  printf '%s\n' "$2" > "$1"
}

merge_deployment_mode() {
  local path="$1" mode="$2"
  if [[ -f "$path" ]]; then
    python3 -c "
import json, sys
with open('$path') as f:
    cfg = json.load(f)
cfg['deploymentMode'] = '$mode'
print(json.dumps(cfg, indent=2))
" > "${path}.tmp" && mv "${path}.tmp" "$path"
  else
    mkdir -p "$(dirname "$path")"
    printf '{"deploymentMode":"%s"}\n' "$mode" > "$path"
  fi
}

is_claude_running() { pgrep -qf "Claude.app/Contents/MacOS/Claude" 2>/dev/null; }

quit_claude() {
  osascript -e 'tell application "Claude" to quit' 2>/dev/null || true
  local deadline=$((SECONDS + 15))
  while is_claude_running && [[ $SECONDS -lt $deadline ]]; do sleep 0.5; done
  is_claude_running && { echo "  Claude did not quit — restart it manually." >&2; return 1; } || true
}

proxy_pid() { lsof -nP -iTCP:"$PROXY_PORT" -sTCP:LISTEN -t 2>/dev/null | head -1; }

stop_proxy() {
  local pid; pid=$(proxy_pid) || true
  [[ -n "$pid" ]] && kill "$pid" 2>/dev/null && sleep 1 || true
}

# ── 1. Preflight ──────────────────────────────────────────────────────────────
echo "=== Claude Desktop gateway setup ==="
require node
require python3

# ── 2. API key for upstream (grid.ai) ─────────────────────────────────────────
mkdir -p "$PROXY_DIR"

if [[ -f "$PROXY_ENV" ]]; then
  # shellcheck disable=SC1090
  source "$PROXY_ENV"
  info "Found saved upstream API key (${PROXY_ENV})"
else
  UPSTREAM_API_KEY=""
fi

if [[ -z "${UPSTREAM_API_KEY:-}" ]]; then
  echo ""
  read -r -p "Enter your grid.ai API key: " UPSTREAM_API_KEY
  [[ -n "$UPSTREAM_API_KEY" ]] || die "API key cannot be empty"
  printf 'UPSTREAM_API_KEY=%s\n' "$UPSTREAM_API_KEY" > "$PROXY_ENV"
  chmod 600 "$PROXY_ENV"
  info "Saved API key to $PROXY_ENV"
fi

# ── 3. Write the proxy server ──────────────────────────────────────────────────
# Build alias map as JS object literal from the parallel arrays above.
JS_ALIAS_MAP="{"
for i in "${!ALIAS_KEYS[@]}"; do
  JS_ALIAS_MAP+="\"${ALIAS_KEYS[$i]}\": \"${ALIAS_VALS[$i]}\","
done
JS_ALIAS_MAP="${JS_ALIAS_MAP%,}}"   # strip trailing comma

cat > "$PROXY_JS" << ENDOFJS
// Auto-generated by setup-claude-gateway.sh — do not edit by hand.
// Translates claude-* alias names (safe for Claude Desktop's validator) to real
// upstream model names on grid.ai, then forwards the request unchanged.
"use strict";
const { createServer } = require("http");

const UPSTREAM      = "${UPSTREAM}";
const UPSTREAM_KEY  = process.env.UPSTREAM_API_KEY || "";
const PROXY_KEY     = "${PROXY_API_KEY}";
const PORT          = parseInt(process.env.PORT || "${PROXY_PORT}", 10);

// alias -> real model
const MODEL_ALIASES = ${JS_ALIAS_MAP};
// real model -> alias (for response rewriting)
const REVERSE       = Object.fromEntries(
  Object.entries(MODEL_ALIASES).map(([a, r]) => [r, a])
);

function rewriteBody(buf) {
  try {
    const json = JSON.parse(buf.toString("utf8"));
    if (json.model && MODEL_ALIASES[json.model]) {
      const real = MODEL_ALIASES[json.model];
      json.model = real;
      return { buf: Buffer.from(JSON.stringify(json), "utf8"), real };
    }
  } catch {}
  return { buf, real: null };
}

const server = createServer(async (req, res) => {
  try {
    const url  = new URL(req.url, \`http://localhost:\${PORT}\`);
    const dest = new URL(url.pathname + url.search, UPSTREAM);
    const log  = (msg) => console.log(\`[\${new Date().toISOString()}] \${msg}\`);

    log(\`\${req.method} \${url.pathname}\`);

    const headers = { ...req.headers };
    headers["host"]          = new URL(UPSTREAM).host;
    headers["authorization"] = \`Bearer \${UPSTREAM_KEY}\`;
    delete headers["content-length"];

    // /v1/models — prepend alias entries so Claude Desktop can select them
    if (req.method === "GET" && /\\/models\\/?$/.test(url.pathname)) {
      const r = await fetch(dest, { headers });
      let payload = await r.text();
      try {
        const j = JSON.parse(payload);
        if (Array.isArray(j.data)) {
          const aliases = Object.keys(MODEL_ALIASES).map((id) => ({
            id, object: "model", created: 1677610602, owned_by: "anthropic",
          }));
          j.data = [...aliases, ...j.data];
          payload = JSON.stringify(j);
        }
      } catch {}
      res.writeHead(r.status, { "content-type": "application/json" });
      res.end(payload);
      return;
    }

    let body = null;
    let real = null;
    if (req.method !== "GET" && req.method !== "HEAD") {
      const chunks = [];
      for await (const chunk of req) chunks.push(chunk);
      ({ buf: body, real } = rewriteBody(Buffer.concat(chunks)));
      headers["content-length"] = String(body.length);
      if (real) log(\`  alias -> \${real}\`);
    }

    const upRes = await fetch(dest, { method: req.method, headers, body });
    const resHeaders = Object.fromEntries(upRes.headers.entries());
    const aliasBack = real ? REVERSE[real] : null;
    if (aliasBack) delete resHeaders["content-length"];
    delete resHeaders["transfer-encoding"];
    res.writeHead(upRes.status, resHeaders);

    if (upRes.body) {
      const reader  = upRes.body.getReader();
      const decoder = aliasBack ? new TextDecoder() : null;
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        if (!res.destroyed) {
          if (aliasBack) {
            res.write(decoder.decode(value, { stream: true })
              .replaceAll(\`"\${real}"\`, \`"\${aliasBack}"\`));
          } else {
            res.write(value);
          }
        }
      }
    }
    res.end();
  } catch (err) {
    console.error("Proxy error:", err);
    if (!res.headersSent) res.writeHead(502);
    res.end(JSON.stringify({ error: err.message }));
  }
});

server.listen(PORT, "127.0.0.1", () => {
  console.log(\`Claude gateway proxy listening on http://127.0.0.1:\${PORT}\`);
  console.log(\`Upstream: \${UPSTREAM}\`);
  console.log(\`Aliases: \${Object.entries(MODEL_ALIASES).map(([a,r])=>\`\${a}->\${r}\`).join(", ")}\`);
});
ENDOFJS

info "Wrote proxy: $PROXY_JS"

# ── 4. Write launchd plist (auto-start on login) ──────────────────────────────
# launchd runs with a minimal PATH; resolve node's absolute path now so the
# plist works even when /usr/local/bin isn't in launchd's environment.
NODE_BIN="$(command -v node)"

mkdir -p "$(dirname "$LAUNCHD_PLIST")"
cat > "$LAUNCHD_PLIST" << ENDOFPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${NODE_BIN}</string>
    <string>${PROXY_JS}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>UPSTREAM_API_KEY</key>
    <string>${UPSTREAM_API_KEY}</string>
    <key>PORT</key>
    <string>${PROXY_PORT}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${PROXY_LOG}</string>
  <key>StandardErrorPath</key>
  <string>${PROXY_LOG}</string>
</dict>
</plist>
ENDOFPLIST

info "Wrote launchd plist: $LAUNCHD_PLIST"

# ── 5. Start/restart the proxy ────────────────────────────────────────────────
# Unload existing launchd job if present (ignore error if not loaded)
launchctl unload "$LAUNCHD_PLIST" 2>/dev/null || true
# Also kill anything else that grabbed the port
stop_proxy

launchctl load "$LAUNCHD_PLIST"

# Wait up to 5 s for the proxy to bind
for i in $(seq 1 10); do
  [[ -n "$(proxy_pid)" ]] && break
  sleep 0.5
done
[[ -n "$(proxy_pid)" ]] || die "Proxy failed to start — check $PROXY_LOG"
info "Proxy running on http://127.0.0.1:${PROXY_PORT} (pid=$(proxy_pid))"

# ── 6. Configure Claude Desktop ───────────────────────────────────────────────
# Build model list JSON from the alias keys array
MODELS_JSON=$(python3 -c "
import json, sys
keys = sys.argv[1:]
print(json.dumps(keys))
" "${ALIAS_KEYS[@]}")

merge_deployment_mode "$NORMAL_DIR/claude_desktop_config.json" "3p"
info "Updated $NORMAL_DIR/claude_desktop_config.json"

merge_deployment_mode "$THIRD_PARTY_DIR/claude_desktop_config.json" "3p"
info "Updated $THIRD_PARTY_DIR/claude_desktop_config.json"

META_CONTENT=$(python3 -c "
import json, os
path = '${CONFIG_LIB}/_meta.json'
meta = {}
if os.path.exists(path):
    try:
        with open(path) as f: meta = json.load(f)
    except: pass
meta['appliedId'] = '${PROFILE_ID}'
entries = [e for e in meta.get('entries', []) if e.get('id') != '${PROFILE_ID}']
entries.append({'id': '${PROFILE_ID}', 'name': '''${GATEWAY_NAME}'''})
meta['entries'] = entries
print(json.dumps(meta, indent=2))
")
write_json "$CONFIG_LIB/_meta.json" "$META_CONTENT"
info "Updated $CONFIG_LIB/_meta.json"

PROFILE_CONTENT=$(python3 -c "
import json
profile = {
    'inferenceProvider': 'gateway',
    'inferenceGatewayBaseUrl': 'http://127.0.0.1:${PROXY_PORT}',
    'inferenceGatewayApiKey': '${PROXY_API_KEY}',
    'inferenceGatewayAuthScheme': 'bearer',
    'inferenceModels': ${MODELS_JSON},
    'disableDeploymentModeChooser': True
}
print(json.dumps(profile, indent=2))
")
write_json "$CONFIG_LIB/${PROFILE_ID}.json" "$PROFILE_CONTENT"
info "Updated $CONFIG_LIB/${PROFILE_ID}.json"

# ── 7. Restart Claude Desktop ────────────────────────────────────────────────
echo ""
echo "Gateway: http://127.0.0.1:${PROXY_PORT} -> ${UPSTREAM}"
echo "Models:"
for i in "${!ALIAS_KEYS[@]}"; do
  printf "  %-28s -> %s\n" "${ALIAS_KEYS[$i]}" "${ALIAS_VALS[$i]}"
done
echo ""

if is_claude_running; then
  read -r -p "Claude Desktop is running. Restart now? [Y/n] " ans
  ans="${ans:-Y}"
  if [[ "$ans" =~ ^[Yy]$ ]]; then
    echo "  Quitting Claude Desktop..."
    quit_claude
    echo "  Opening Claude Desktop..."
    open -a Claude
    info "Restarted"
  else
    echo "  Restart Claude Desktop manually for changes to take effect."
  fi
else
  echo "  Opening Claude Desktop..."
  open -a Claude
  info "Opened"
fi

echo ""
echo "Done."
echo "  Proxy log:  tail -f $PROXY_LOG"
echo "  Stop proxy: launchctl unload $LAUNCHD_PLIST"
echo "  Reset app:  ./reset-claude.sh"
